[theme]
primaryColor = "#1A6CE7"
secondaryTextColor= "#5D6A85"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ECEEF1"
codeBackgroundColor = "#fbfbfb"
textColor = "#1E252F"
linkColor = "#085BD7"
borderColor = "#D5DAE4"
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "8px"
buttonRadius = "8px"
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
headingFont = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap"
codeFontSize = "13px"
codeTextColor = "#002C6E"
baseFontSize = 14
baseFontWeight = 400
headingFontSizes = ["36px", "24px", "20px", "16px", "14px", "12px"]
headingFontWeights = [600, 600, 600, 500, 500, 500]
linkUnderline = false
chartCategoricalColors = ["#1A6CE7", "#51CAA5", "#ECB700", "#FF7C1D", "#DE350B", "#6554C0", "#FFAB00", "#00A3BF"]

blueColor = "#1A6CE7"
blueBackgroundColor = "#F1F7FF"
blueTextColor = "#004CBE"

greenColor = "#51CAA5"
greenBackgroundColor = "#EEFBF6"
greenTextColor = "#137054"

yellowColor = "#ECB700"
yellowBackgroundColor = "#FFFBEB"
yellowTextColor = "#BC9201"

orangeColor = "#FF7C1D"
orangeBackgroundColor = "#FFF5EC"
orangeTextColor = "#934812"

redColor = "#D3132F"
redBackgroundColor = "#FEF2F3"
redTextColor = "#A40319"

violetColor = "#D45CFF"
violetBackgroundColor = "#FBF3FF"
violetTextColor = "#762D91"

dataframeBorderColor = "#D5DAE4"
dataframeHeaderBackgroundColor = "#fbfbfb"

[theme.sidebar]
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#fbfbfb"
textColor = "#1E252F"
borderColor = "#D5DAE4"
